# Deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: { { .Values.namespace | default "quiz" } }
  labels:
    app: frontend
spec:
  replicas: { { .Values.replicaCount } }
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: VITE_REACT_APP_API_URL
              value: { { .Values.env.VITE_REACT_APP_API_URL | quote } }
          ports:
            - containerPort: { { .Values.service.port } }
---
# Service.yaml
apiVersion: v1
kind: Service
metadata:
  name: { { .Values.service.name } }
  namespace: { { .Values.namespace | default "quiz" } }
spec:
  selector:
    app: frontend
  ports:
    - port: { { .Values.service.port } }
      protocol: TCP
  type: { { .Values.service.type } }
